Fix: fix and update debian files

diff --git a/gradle/gradle/scripts/openbaton-fms b/gradle/gradle/scripts/openbaton-fms
--- a/gradle/gradle/scripts/openbaton-fms
+++ b/gradle/gradle/scripts/openbaton-fms
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 
 # Copyright (c) 2015-2016 Fraunhofer FOKUS
 # Licensed under the Apache License, Version 2.0 (the "License");
@@ -13,113 +13,130 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-source ./gradle.properties
 
-_version=${version}
-_fmsystem_config_file=/etc/openbaton/fms.properties
+##########################
+#### General Settings ####
+##########################
 
-function check_already_running {
-        result=$(ps au | grep -v grep | grep fault-management-system | wc -l);
-        if [ "${result}" -ne "0" ]; then
-                echo "The fault-management-system is already running.."
-		exit;
-        fi
-}
-function start_mysql_osx {
-    sudo /usr/local/mysql/support-files/mysql.server start
-}
+set -e
+set -u
+#set -x # only for DEBUG
 
-function start_mysql_linux {
+# Make available the functions defined in /lib/lsb/init-functions
+. /lib/lsb/init-functions
+
+
+##########################
+#### Global Variables ####
+##########################
+
+OPENBATON_COMPONENT_NAME_FANCY="Fault Management System (FMS)"
+OPENBATON_COMPONENT_NAME=fms
+OPENBATON_COMPONENT_RELATIVE_SUBPATH=fms
+
+OPENBATON_COMPONENT_CONFIG_FILE=/etc/openbaton/openbaton-${OPENBATON_COMPONENT_NAME}.properties
+OPENBATON_COMPONENT_JAR_FILE_NAME=openbaton-${OPENBATON_COMPONENT_NAME}
+OPENBATON_COMPONENT_JAR_INSTALL_DIR=/usr/lib/openbaton/${OPENBATON_COMPONENT_RELATIVE_SUBPATH}
+
+OPENBATON_COMPONENT_PID_FILE=/var/run/openbaton-${OPENBATON_COMPONENT_NAME}.pid
+DAEMON_USER=root
+OSTYPE=$(uname)
+
+
+###############
+#### MySQL ####
+###############
+
+start_mysql () {
     sudo service mysql start
 }
 
-function check_mysql {
-    if [[ "$OSTYPE" == "linux-gnu" ]]; then
-	result=$(pgrep mysql | wc -l);
-        if [ ${result} -eq 0 ]; then
-                read -p "mysql is down, would you like to start it ([y]/n):" yn
-		case $yn in
-			[Yy]* ) start_mysql_linux ; break;;
-			[Nn]* ) echo "you can't proceed withuot having mysql up and running" 
-				exit;;
-			* ) start_mysql_linux;;
-		esac
-        fi
-    elif [[ "$OSTYPE" == "darwin"* ]]; then
-	mysqladmin status
-	result=$?
-        if [ "${result}" -eq "0" ]; then
-                echo "mysql service running..."
-        else
-                read -p "mysql is down, would you like to start it ([y]/n):" yn
-                case $yn in
-                        [Yy]* ) start_mysql_osx ; break;;
-                        [Nn]* ) exit;;
-                        * ) start_mysql_osx;;
-                esac
-        fi
+check_mysql () {
+    instance=$(ps aux | grep -v grep | grep "mysql" | wc -l)
+    if [ ${instance} -eq 0 ] ; then
+        log_warning_msg "MySQL is not running"
+        read -p "MySQL is down, would you like to start it (Y/n):" yn
+        case $yn in
+            [Yy]* ) start_mysql ;
+                    break ;;
+            [Nn]* ) log_failure_msg "You can't proceed withuot having MySQL up and running"
+                    exit 1 ;;
+            * ) start_mysql;;
+        esac
     fi
 }
-function check_zabbix_plugin_up {
-        result=$(ps au | grep -v grep | grep zabbix-plugin | wc -l);
-        if [ "${result}" -eq "0" ]; then
-                echo "The zabbix-plugin is not running. The fault management system cannot start"
-		exit;
-        fi
-}
-function usage {
-    echo -e "Open Baton Fault Management System\n"
-    echo -e "Usage:\n\t ./fm-system.sh [compile|start|stop|force-stop]"
-}
-function stop {
-    pkill -f fm-system-${_version}.jar
-}
 
-function start {
 
-    if [ ! -d build/  ]
-        then
-            compile
+####################
+#### Open Baton ####
+####################
+
+check_already_running () {
+    instance=$(ps aux | grep -v grep | grep "${OPENBATON_COMPONENT_JAR_FILE_NAME}" | grep "jar" | wc -l)
+    if [ ${instance} -ne 0 ]; then
+        log_warning_msg "The Open Baton ${OPENBATON_COMPONENT_NAME_FANCY} is already running"
+        exit 1
     fi
-    
+}
+
+set_jar_version () {
+    openbaton_component_jar_file_name_versioned=$(ls -ct ${OPENBATON_COMPONENT_JAR_INSTALL_DIR} | grep "${OPENBATON_COMPONENT_JAR_FILE_NAME}" | grep "jar" | head -n 1)
+    if [ ${openbaton_component_jar_file_name_versioned} = "" ]; then
+        log_failure_msg "The Open Baton ${OPENBATON_COMPONENT_NAME_FANCY} is not installed (jar-file not found)"
+        exit 1
+    fi
+}
+
+configure () {
     check_already_running
     check_mysql
-    check_zabbix_plugin_up
-    if [ 0 -eq $? ]
-        then
-	    java -jar "build/libs/openbaton-fm-$_version.jar" --spring.config.location=file:${_fmsystem_config_file}
-    fi
+    set_jar_version
 }
 
-if [ $# -eq 0 ]
-   then
-        usage
-        exit 1
+start () {
+    configure
+    log_success_msg "Starting the Open Baton ${OPENBATON_COMPONENT_NAME_FANCY} .."
+    start-stop-daemon --start --background --pidfile ${OPENBATON_COMPONENT_PID_FILE} --make-pidfile --user ${DAEMON_USER} --chuid ${DAEMON_USER} --exec /usr/bin/java -- -jar ${OPENBATON_COMPONENT_JAR_INSTALL_DIR}/${openbaton_component_jar_file_name_versioned} --spring.config.location=file:${OPENBATON_COMPONENT_CONFIG_FILE}
+}
+
+stop () {
+    log_success_msg "Stopping the Open Baton ${OPENBATON_COMPONENT_NAME_FANCY} .."
+    start-stop-daemon --stop --pidfile ${OPENBATON_COMPONENT_PID_FILE}
+}
+
+restart () {
+    stop
+    start
+}
+
+usage () {
+    echo "Open Baton ${OPENBATON_COMPONENT_NAME_FANCY}"
+    echo "Usage:\n\t [openbaton-${OPENBATON_COMPONENT_NAME} start|stop|restart] | [service openbaton-${OPENBATON_COMPONENT_NAME} start|stop|restart] | [start|stop openbaton-${OPENBATON_COMPONENT_NAME}] | [systemctl start|stop openbaton-${OPENBATON_COMPONENT_NAME}.service]"
+}
+
+
+##
+#   MAIN
+##
+
+if [ ${#} -eq 0 ]; then
+    usage
+    exit 1
 fi
 
-
-declare -a cmds=($@)
-for (( i = 0; i <  ${#cmds[*]}; ++ i ))
+for cmd in ${@}
 do
-    case ${cmds[$i]} in
-        "sc" )
-            clean
-            compile
-            start ;;
+    case ${cmd} in
         "start" )
             start ;;
-        "clean" )
-            clean ;;
         "stop" )
             stop ;;
-        "compile" )
-            compile ;;
-        * )
-            usage
-            end ;;
+        "restart" )
+            restart ;;
+        *)
+            usage;;
     esac
-    if [[ $? -ne 0 ]]; 
-    then
-	    exit 1
+    if [ $? -ne 0 ]; then
+        exit 1
     fi
 done
